//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v2rayP.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("v2rayP.Resources.Localization.I18n", typeof(I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is coming soon!.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string FormAbout {
            get {
                return ResourceManager.GetString("FormAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Servers.
        /// </summary>
        public static string FormEditServers {
            get {
                return ResourceManager.GetString("FormEditServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string FormSetting {
            get {
                return ResourceManager.GetString("FormSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string FormShowLog {
            get {
                return ResourceManager.GetString("FormShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logging.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuGroupHelp {
            get {
                return ResourceManager.GetString("MenuGroupHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC.
        /// </summary>
        public static string MenuGroupPAC {
            get {
                return ResourceManager.GetString("MenuGroupPAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Mode.
        /// </summary>
        public static string MenuGroupProxyMode {
            get {
                return ResourceManager.GetString("MenuGroupProxyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servers.
        /// </summary>
        public static string MenuGroupServers {
            get {
                return ResourceManager.GetString("MenuGroupServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuItemAbout {
            get {
                return ResourceManager.GetString("MenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Update.
        /// </summary>
        public static string MenuItemCheckForUpdate {
            get {
                return ResourceManager.GetString("MenuItemCheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy PAC Script URL.
        /// </summary>
        public static string MenuItemCopyPACScriptURL {
            get {
                return ResourceManager.GetString("MenuItemCopyPACScriptURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Mode.
        /// </summary>
        public static string MenuItemDirectMode {
            get {
                return ResourceManager.GetString("MenuItemDirectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Servers.
        /// </summary>
        public static string MenuItemEditServers {
            get {
                return ResourceManager.GetString("MenuItemEditServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Rules.
        /// </summary>
        public static string MenuItemEditUserRules {
            get {
                return ResourceManager.GetString("MenuItemEditUserRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItemExit {
            get {
                return ResourceManager.GetString("MenuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string MenuItemFeedback {
            get {
                return ResourceManager.GetString("MenuItemFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Mode.
        /// </summary>
        public static string MenuItemGlobalMode {
            get {
                return ResourceManager.GetString("MenuItemGlobalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep System Proxy.
        /// </summary>
        public static string MenuItemKeepSystemProxyMode {
            get {
                return ResourceManager.GetString("MenuItemKeepSystemProxyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC Mode.
        /// </summary>
        public static string MenuItemPacMode {
            get {
                return ResourceManager.GetString("MenuItemPacMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string MenuItemSetting {
            get {
                return ResourceManager.GetString("MenuItemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log.
        /// </summary>
        public static string MenuItemShowLog {
            get {
                return ResourceManager.GetString("MenuItemShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update GFWList.
        /// </summary>
        public static string MenuItemUpdateGFWList {
            get {
                return ResourceManager.GetString("MenuItemUpdateGFWList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki.
        /// </summary>
        public static string MenuItemWiki {
            get {
                return ResourceManager.GetString("MenuItemWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find {0} in {1}.
        /// </summary>
        public static string MsgCantFindV2Ray {
            get {
                return ResourceManager.GetString("MsgCantFindV2Ray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to initialize directory for {0}. please make sure directory &quot;{1}&quot; is not occupied..
        /// </summary>
        public static string MsgFailToCreateDirectoryFor {
            get {
                return ResourceManager.GetString("MsgFailToCreateDirectoryFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize Privoxy..
        /// </summary>
        public static string MsgFailToExtractPrivoxy {
            get {
                return ResourceManager.GetString("MsgFailToExtractPrivoxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write JSON file to {0}. Reason: {1}..
        /// </summary>
        public static string MsgFailToWriteJSON {
            get {
                return ResourceManager.GetString("MsgFailToWriteJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update GFWList via direct link due to inactivity of v2ray core program.
        /// </summary>
        public static string MsgFallbackToDirectUpdateGFWList {
            get {
                return ResourceManager.GetString("MsgFallbackToDirectUpdateGFWList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been running..
        /// </summary>
        public static string MsgInstanceExist {
            get {
                return ResourceManager.GetString("MsgInstanceExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input a server address..
        /// </summary>
        public static string MsgPleaseInputAddress {
            get {
                return ResourceManager.GetString("MsgPleaseInputAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input VMess user id..
        /// </summary>
        public static string MsgPleaseInputId {
            get {
                return ResourceManager.GetString("MsgPleaseInputId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}!
        ///Range: {1}
        ///Default: {2}.
        /// </summary>
        public static string MsgPleaseInvalidNumberField {
            get {
                return ResourceManager.GetString("MsgPleaseInvalidNumberField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select {0} from given values..
        /// </summary>
        public static string MsgPleaseSelectGivenValues {
            get {
                return ResourceManager.GetString("MsgPleaseSelectGivenValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start v2ray-core failed, please check the log for detail..
        /// </summary>
        public static string MsgV2RayFailedToStart {
            get {
                return ResourceManager.GetString("MsgV2RayFailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start v2ray-core because v2ray core doesn&apos;t exist, please put it in the folder &quot;{0}&quot;.
        /// </summary>
        public static string MsgV2RayFailedToStartDueToInexistence {
            get {
                return ResourceManager.GetString("MsgV2RayFailedToStartDueToInexistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The v2ray-core is too old. The minimum required version is {0}.
        /// </summary>
        public static string MsgV2RayIsTooOld {
            get {
                return ResourceManager.GetString("MsgV2RayIsTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2Ray Server.
        /// </summary>
        public static string NewV2RayServer {
            get {
                return ResourceManager.GetString("NewV2RayServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Available Servers.
        /// </summary>
        public static string NoAvailableServers {
            get {
                return ResourceManager.GetString("NoAvailableServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode: {0}
        ///Server: {1}.
        /// </summary>
        public static string NotifyIconTextTemplate {
            get {
                return ResourceManager.GetString("NotifyIconTextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Mode.
        /// </summary>
        public static string ProxyModeDirect {
            get {
                return ResourceManager.GetString("ProxyModeDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Mode.
        /// </summary>
        public static string ProxyModeGlobal {
            get {
                return ResourceManager.GetString("ProxyModeGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep System Proxy.
        /// </summary>
        public static string ProxyModeKeepSystemProxy {
            get {
                return ResourceManager.GetString("ProxyModeKeepSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC Mode.
        /// </summary>
        public static string ProxyModePac {
            get {
                return ResourceManager.GetString("ProxyModePac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept LAN Connections.
        /// </summary>
        public static string SettingFormAcceptLAN {
            get {
                return ResourceManager.GetString("SettingFormAcceptLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoStart.
        /// </summary>
        public static string SettingFormAutoStart {
            get {
                return ResourceManager.GetString("SettingFormAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Access Log.
        /// </summary>
        public static string SettingFormEnableAccessLog {
            get {
                return ResourceManager.GetString("SettingFormEnableAccessLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Error Log.
        /// </summary>
        public static string SettingFormEnableErrorLog {
            get {
                return ResourceManager.GetString("SettingFormEnableErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GFWList URL:.
        /// </summary>
        public static string SettingFormGFWListURL {
            get {
                return ResourceManager.GetString("SettingFormGFWListURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Proxy Port.
        /// </summary>
        public static string SettingFormHTTPPort {
            get {
                return ResourceManager.GetString("SettingFormHTTPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Proxy Setting.
        /// </summary>
        public static string SettingFormLocalProxySetting {
            get {
                return ResourceManager.GetString("SettingFormLocalProxySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level:.
        /// </summary>
        public static string SettingFormLogLevel {
            get {
                return ResourceManager.GetString("SettingFormLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC Server Port:.
        /// </summary>
        public static string SettingFormPACServerPort {
            get {
                return ResourceManager.GetString("SettingFormPACServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCK5 Proxy Port:.
        /// </summary>
        public static string SettingFormSOCKPort {
            get {
                return ResourceManager.GetString("SettingFormSOCKPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Via Proxy.
        /// </summary>
        public static string SettingFormUpdateViaProxy {
            get {
                return ResourceManager.GetString("SettingFormUpdateViaProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v2rayP Setting.
        /// </summary>
        public static string SettingFormV2RayPSetting {
            get {
                return ResourceManager.GetString("SettingFormV2RayPSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update GFWList..
        /// </summary>
        public static string UpdateGFWListFailed {
            get {
                return ResourceManager.GetString("UpdateGFWListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated GFWList..
        /// </summary>
        public static string UpdateGFWListSuccess {
            get {
                return ResourceManager.GetString("UpdateGFWListSuccess", resourceCulture);
            }
        }
    }
}
